services:
  homeassistant:
    container_name: homeassistant
    hostname: homeassistant
    image: "homeassistant/home-assistant:${CONTAINER_HASS_VERSION}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${HASS_HOME}/hass/config:/config
    restart: unless-stopped
    privileged: true
    network_mode: host

  ewelink_smart_home:
    image: 5idns/ewelink_smart_home
    restart: unless-stopped
    network_mode: host
    environment:
      - HA_URL=http://localhost:8123
      - SUPERVISOR_TOKEN=${SUPERVISOR_TOKEN}
    volumes:
      - ${HASS_HOME}/data:/data