services:
  homeassistant:
    container_name: homeassistant
    hostname: homeassistant
    image: "homeassistant/home-assistant:${CONTAINER_HASS_VERSION}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${HASS_HOME}/hass/config:/config
    restart: unless-stopped
    privileged: true
    network_mode: host
