version: '3'
services:
  homeassistant:
    container_name: homeassistant
    hostname: homeassistant
    image: "homeassistant/home-assistant:latest"
    environment:
      - trusted_proxies=${IP_PROXY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${HASS_HOME}/hass/config:/config
    restart: unless-stopped
    privileged: true
    network_mode: host
